name:                mdpc
version:             0.1.0.0
github:              "https://github.com/vka4git/mdpc"
license:             BSD3
author:              "Vladimir Morozov"
maintainer:          "me.morozovvp@gmail.com"
copyright:           "2019 Vladimir Morozov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mdpc#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  mdpc:
    main:                MDPC.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mdpc

